-- The import cache: where extracted data lives between sessions.
--
-- The cache holds data *derived* from the cartridge, never a copy of it. Each
-- game gets its own directory so Gold, Silver, and Crystal can coexist, and a
-- manifest records which dump produced it. When the cache format changes the
-- FORMAT_VERSION is bumped and stale caches are re-imported rather than
-- half-read.

local cache = {}

-- Bump whenever the on-disk layout or any decoder's output changes shape.
--
-- 2 adds the Pokédex entries. A cache written before them would load and run,
-- with an empty dex and no sign of why, which is exactly the half-read state
-- this number exists to prevent. 3 adds the status cures, for the same reason:
-- without them every Antidote in the game silently does nothing. 4 adds the
-- whirlpool value, without which the sea is quietly open. 5 adds the music
-- banks and the music id on each map, without which the game plays in silence
-- and never says why.
cache.FORMAT_VERSION = 5

local ROOT = "cache"

function cache.dir(game)
  return ("%s/%s"):format(ROOT, game)
end

function cache.manifest_path(game)
  return ("%s/manifest.lua"):format(cache.dir(game))
end

--- Serialise a Lua value as loadable source.
--
-- Deliberately minimal: the extracted data is plain arrays, maps, numbers and
-- strings. Anything else is a bug in a decoder and should fail loudly here
-- rather than be silently dropped.
local function serialize(value, indent)
  indent = indent or ""
  local next_indent = indent .. "  "
  local kind = type(value)

  if kind == "number" or kind == "boolean" then
    return tostring(value)
  elseif kind == "string" then
    return string.format("%q", value)
  elseif kind == "nil" then
    return "nil"
  elseif kind ~= "table" then
    error(("cannot serialise a %s into the cache"):format(kind))
  end

  -- Array part first, then the remaining keys sorted so output is stable and
  -- diffs between two imports are readable.
  local parts = {}
  local array_length = #value
  for i = 1, array_length do
    parts[#parts + 1] = next_indent .. serialize(value[i], next_indent)
  end

  local keys = {}
  for k in pairs(value) do
    if not (type(k) == "number" and k >= 1 and k <= array_length and k % 1 == 0) then
      keys[#keys + 1] = k
    end
  end
  table.sort(keys, function(a, b)
    return tostring(a) < tostring(b)
  end)

  for _, k in ipairs(keys) do
    local key_source
    if type(k) == "string" and k:match("^[%a_][%w_]*$") then
      key_source = k
    else
      key_source = "[" .. serialize(k, next_indent) .. "]"
    end
    parts[#parts + 1] = ("%s%s = %s")
      :format(next_indent, key_source, serialize(value[k], next_indent))
  end

  if #parts == 0 then
    return "{}"
  end
  return "{\n" .. table.concat(parts, ",\n") .. ",\n" .. indent .. "}"
end

cache.serialize = serialize

function cache.ensure(game)
  local ok, err = love.filesystem.createDirectory(cache.dir(game))
  if not ok then
    return nil, ("could not create cache directory %s: %s")
      :format(cache.dir(game), tostring(err))
  end
  return true
end

--- Write one extracted table as a loadable Lua module.
function cache.write(game, name, value)
  local path = ("%s/%s.lua"):format(cache.dir(game), name)
  local source = "-- Generated by gen2recomp's importer. Do not edit.\nreturn "
    .. serialize(value) .. "\n"
  local ok, err = love.filesystem.write(path, source)
  if not ok then
    return nil, ("could not write %s: %s"):format(path, tostring(err))
  end
  return path, #source
end

--- Write a PNG next to the data tables.
function cache.write_image(game, name, image_data)
  local path = ("%s/%s.png"):format(cache.dir(game), name)
  local encoded = image_data:encode("png")
  local ok, err = love.filesystem.write(path, encoded:getString())
  if not ok then
    return nil, ("could not write %s: %s"):format(path, tostring(err))
  end
  return path
end

--- Load a previously extracted table. Returns nil when absent.
function cache.read(game, name)
  local path = ("%s/%s.lua"):format(cache.dir(game), name)
  if not love.filesystem.getInfo(path) then
    return nil
  end
  local chunk, err = love.filesystem.load(path)
  if not chunk then
    return nil, ("cache file %s is corrupt: %s"):format(path, tostring(err))
  end
  local ok, value = pcall(chunk)
  if not ok then
    return nil, ("cache file %s failed to load: %s"):format(path, tostring(value))
  end
  return value
end

--- Is there a usable cache for this game, written by this format version?
function cache.is_current(game)
  local manifest = cache.read(game, "manifest")
  if not manifest then
    return false
  end
  return manifest.format_version == cache.FORMAT_VERSION, manifest
end

function cache.list_games()
  local games = {}
  if not love.filesystem.getInfo(ROOT) then
    return games
  end
  for _, entry in ipairs(love.filesystem.getDirectoryItems(ROOT)) do
    local current, manifest = cache.is_current(entry)
    if manifest then
      games[#games + 1] = { game = entry, current = current, manifest = manifest }
    end
  end
  return games
end

--- Remove a game's cache. Used when a re-import is requested and when a stale
-- format version is found.
function cache.clear(game)
  local dir = cache.dir(game)
  if not love.filesystem.getInfo(dir) then
    return true
  end
  for _, entry in ipairs(love.filesystem.getDirectoryItems(dir)) do
    love.filesystem.remove(("%s/%s"):format(dir, entry))
  end
  return love.filesystem.remove(dir)
end

function cache.location()
  return love.filesystem.getSaveDirectory() .. "/" .. ROOT
end

return cache
